### ISSUE TITLE
Building addon

### ISSUE THREAD

**Issue by abramsba** [JustOscarMike/iBuild#1]
I've never had to build an add-on from the source, I can't really find any resources that seem relevant enough to help me out. Through Arma tools on Steam I used the Addon Builder. I tried from both the git root and the source folder root (where config.cpp is). I can see the classes in the editor such as `iBuild_Door` but there are no modules or menus that I can open in the game. I receive an error message, `Script NerdMods_iBuild\NMIB_Core\iBuild_Init.sqf not found`. The .pbo file I ended up with looks like:

![](http://i.imgur.com/GoVUK6x.jpg)

I know you've since stopped but in the event that you're around, am I missing a step somewhere or using the wrong program?

**Comment by JustOscarMike** [comment]
Hey @abramsba,

Sorry you've had to wait 6 days for a reply. I've only just noticed the email notification...
Did you manage to work it out, or do you still need help?

> Script NerdMods_iBuild\NMIB_Core\iBuild_Init.sqf not found

The above error would suggest that you don't have the pbo packaged correctly. The root folder of the pbo should be named: **Nerdmods_iBuild** with the rest of the folders contained within it.

Your pbo is also missing the NMIB_Core folder among many others. My guess is that you're compiling from the wrong directory or the compile process is failing somewhere and not including all the required files.

**Comment by JustOscarMike** [comment]
Hey @abramsba,

Sorry you've had to wait 6 days for a reply. I've only just noticed the email notification...
Did you manage to work it out, or do you still need help?

> Script NerdMods_iBuild\NMIB_Core\iBuild_Init.sqf not found

The above error would suggest that you don't have the pbo packaged correctly. The root folder of the pbo should be named: **Nerdmods_iBuild** with the rest of the folders contained within it.

Your pbo is also missing the **NMIB_Core** folder among many others. My guess is that you're compiling from the wrong directory or the compile process is failing somewhere and not including all the required files.
1. Download and extract **iBuild-master.zip**
2. Right-click **Nerdmods_iBuild** folder and select **PBO Manager > Pack into "Nerdmods_iBuild.pbo"**

![capture](https://cloud.githubusercontent.com/assets/18622450/17634642/9558b9d0-60cb-11e6-9cb3-8d7151f36019.PNG)

**Comment by abramsba** [comment]
No problem, there is no urgency.

I didn't notice that PBO manager was integrated with explorer, I had been using the Addon Builder application from Arma 3 Tools. It didn't include the source directories when building the addon.

Doing it via PBO manager works and I'm able to load it up and tinker around. Thanks for the help.
